// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vozila.DataAccess.DataContext;

#nullable disable

namespace Vozila.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203115016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vozila.Domain.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShipingAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Thessaloniki",
                            Country = "GR",
                            CustomerName = "KNAUF GYPSOPIIA S.A.",
                            ShipingAddress = "EYRIPIDOU 10"
                        },
                        new
                        {
                            Id = 2,
                            City = "Zagreb",
                            Country = "HR",
                            CustomerName = "Transporti d.o.o.",
                            ShipingAddress = "Ulica 2"
                        },
                        new
                        {
                            Id = 3,
                            City = "Sofia",
                            Country = "BG",
                            CustomerName = "Logistika d.o.o.",
                            ShipingAddress = "Ulica 3"
                        });
                });

            modelBuilder.Entity("Vozila.Domain.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<decimal>("ContractOilPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Conditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = 1,
                            ContractOilPrice = 70.5m
                        },
                        new
                        {
                            Id = 2,
                            ContractId = 2,
                            ContractOilPrice = 69.0m
                        },
                        new
                        {
                            Id = 3,
                            ContractId = 3,
                            ContractOilPrice = 71.2m
                        });
                });

            modelBuilder.Entity("Vozila.Domain.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("TransporterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValueEUR")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractNumber = "CTR-2025-001",
                            CreatedDate = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TransporterId = 1,
                            ValidUntil = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueEUR = 15000.00m
                        },
                        new
                        {
                            Id = 2,
                            ContractNumber = "CTR-2025-002",
                            CreatedDate = new DateTime(2025, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TransporterId = 2,
                            ValidUntil = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueEUR = 12000.00m
                        },
                        new
                        {
                            Id = 3,
                            ContractNumber = "CTR-2025-003",
                            CreatedDate = new DateTime(2025, 1, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TransporterId = 3,
                            ValidUntil = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValueEUR = 18000.00m
                        });
                });

            modelBuilder.Entity("Vozila.Domain.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DailyPricePerLiter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DestinationContractPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("ContractId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Ljubljana",
                            ConditionId = 1,
                            Country = "Slo",
                            DailyPricePerLiter = 70.0m,
                            DestinationContractPrice = 150m
                        },
                        new
                        {
                            Id = 2,
                            City = "Zagreb",
                            ConditionId = 1,
                            Country = "HR",
                            DailyPricePerLiter = 70.0m,
                            DestinationContractPrice = 120m
                        },
                        new
                        {
                            Id = 3,
                            City = "Belgrade",
                            ConditionId = 2,
                            Country = "SRB",
                            DailyPricePerLiter = 68.5m,
                            DestinationContractPrice = 180m
                        },
                        new
                        {
                            Id = 4,
                            City = "Bucharest",
                            ConditionId = 2,
                            Country = "RO",
                            DailyPricePerLiter = 68.5m,
                            DestinationContractPrice = 200m
                        },
                        new
                        {
                            Id = 5,
                            City = "Sofia",
                            ConditionId = 3,
                            Country = "BG",
                            DailyPricePerLiter = 71.0m,
                            DestinationContractPrice = 175m
                        },
                        new
                        {
                            Id = 6,
                            City = "Thessaloniki",
                            ConditionId = 3,
                            Country = "GR",
                            DailyPricePerLiter = 71.0m,
                            DestinationContractPrice = 220m
                        },
                        new
                        {
                            Id = 7,
                            City = "Prishtina",
                            ConditionId = 1,
                            Country = "RKS",
                            DailyPricePerLiter = 70.0m,
                            DestinationContractPrice = 160m
                        },
                        new
                        {
                            Id = 8,
                            City = "Skopje",
                            ConditionId = 2,
                            Country = "MK",
                            DailyPricePerLiter = 68.5m,
                            DestinationContractPrice = 155m
                        });
                });

            modelBuilder.Entity("Vozila.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelledReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("ContractOilPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateForLoadingFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateForLoadingTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TransporterId")
                        .HasColumnType("int");

                    b.Property<string>("TruckPlateNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TruckSubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TransporterId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            ContractOilPrice = 70.5m,
                            CreatedDate = new DateTime(2025, 1, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            DateForLoadingFrom = new DateTime(2025, 1, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateForLoadingTo = new DateTime(2025, 1, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 1,
                            Status = "Pending",
                            TransporterId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            ContractOilPrice = 69.0m,
                            CreatedDate = new DateTime(2025, 1, 11, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            DateForLoadingFrom = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DateForLoadingTo = new DateTime(2025, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 3,
                            Status = "Pending",
                            TransporterId = 2
                        });
                });

            modelBuilder.Entity("Vozila.Domain.Models.PriceOil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyPricePerLiter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("PriceOils");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyPricePerLiter = 70.0m,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DailyPricePerLiter = 68.5m,
                            Date = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Vozila.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transporter"
                        });
                });

            modelBuilder.Entity("Vozila.Domain.Models.Transporter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Transporters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "TransLogistika DOOEL",
                            ContactPerson = "Petar Petrovski",
                            Email = "info@translogistika.mk",
                            PhoneNumber = "+389 70 123 456"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Balkan Transport Group",
                            ContactPerson = "Milan Jovanovic",
                            Email = "office@balkantransport.rs",
                            PhoneNumber = "+381 64 987 6543"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "EuroCargo Solutions",
                            ContactPerson = "Ivan Petrović",
                            Email = "contact@eurocargo.hr",
                            PhoneNumber = "+385 91 332 4422"
                        });
                });

            modelBuilder.Entity("Vozila.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("TransporterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("RoleId");

                    b.HasIndex("TransporterId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "System Admin",
                            IsActive = true,
                            Password = "admin123",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Transporter User",
                            IsActive = true,
                            Password = "trans123",
                            RoleId = 2,
                            TransporterId = 1
                        });
                });

            modelBuilder.Entity("Vozila.Domain.Models.Condition", b =>
                {
                    b.HasOne("Vozila.Domain.Models.Contract", "Contract")
                        .WithMany("Conditions")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Vozila.Domain.Models.Contract", b =>
                {
                    b.HasOne("Vozila.Domain.Models.Transporter", "Transporter")
                        .WithMany("Contracts")
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("Vozila.Domain.Models.Destination", b =>
                {
                    b.HasOne("Vozila.Domain.Models.Condition", "Condition")
                        .WithMany("Destinations")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vozila.Domain.Models.Contract", null)
                        .WithMany("Destinations")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Condition");
                });

            modelBuilder.Entity("Vozila.Domain.Models.Order", b =>
                {
                    b.HasOne("Vozila.Domain.Models.User", "CancelledByUser")
                        .WithMany("Orders")
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vozila.Domain.Models.Company", "Company")
                        .WithMany("Orders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vozila.Domain.Models.Destination", "Destination")
                        .WithMany("Orders")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vozila.Domain.Models.Transporter", "Transporter")
                        .WithMany("Orders")
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("Company");

                    b.Navigation("Destination");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("Vozila.Domain.Models.User", b =>
                {
                    b.HasOne("Vozila.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vozila.Domain.Models.Transporter", "Transporter")
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("Vozila.Domain.Models.Company", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Vozila.Domain.Models.Condition", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Vozila.Domain.Models.Contract", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Vozila.Domain.Models.Destination", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Vozila.Domain.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Vozila.Domain.Models.Transporter", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Vozila.Domain.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
